# CONFIGURACIÓN GLOBAL (constantes)

config:
  match:
    max_races: 5
  race:
    max_players: 8
    max_NPCs : 25
    time_limit_sec: 6000        # límite por carrera (10 minutos)
    intermission_sec: 10       # pausa entre carreras

# Penalizaciones por mejoras de auto
# (se suman en segundos al tiempo de carrera)
upgrades:
  max_speed:
    delta: 5.0        # cuánto suma cada upgrade
    penalty: 3.0
  acceleration:
    delta: 10.0
    penalty: 2.0
  nitro:
    delta: 2.0
    penalty: 1.5
  health:
    delta: 20.0
    penalty: 1.0
# ===================================
# TIPOS DE AUTOS DISPONIBLES
# ===================================
car_types:
  - name: "Speedster"
    width: 1.5
    height: 1.9
    description: "Rápido pero frágil"
    max_speed: 500 #m/s
    acceleration: 80 #m/s^2
    control: 8.8
    health: 100
    mass: 1.2
    nitro_multiplier: 2.0
    nitro_duration: 3
    nitro_cooldown: 5
    density: 0.9
    friction: 0.6
    restitution: 0.2
    linear_damping: 1.5
    angular_damping: 6.0
    drift_factor: 0.36 #0.0 mucho drift , 1.0 casi nada

  - name: "Tank"
    width: 3.6
    height: 1.6
    description: "Lento pero indestructible"
    max_speed: 300
    acceleration: 130
    control: 7.7
    health: 200
    mass: 1.8
    nitro_multiplier: 1.3
    nitro_duration: 4
    nitro_cooldown: 6
    density: 1.5
    friction: 0.2
    restitution: 0.05
    linear_damping: 0.9
    angular_damping: 5.0
    drift_factor: 0.56

  - name: "Drifter"
    width: 2.0
    height: 1.4
    description: "Buen control y derrapes suaves"
    max_speed: 380
    acceleration: 150
    control: 9.2
    health: 100
    mass: 1.0
    nitro_multiplier: 1.6
    nitro_duration: 3
    nitro_cooldown: 5
    density: 1.2
    friction: 0.1
    restitution: 0.15
    linear_damping: 0.9
    angular_damping: 5.0
    drift_factor: 0.01

  - name: "Rocket"
    width: 2.5
    height: 1.5
    description: "Aceleración brutal pero poca maniobra"
    max_speed: 640
    acceleration: 210
    control: 9.4
    health: 100
    mass: 0.9
    nitro_multiplier: 2.0
    nitro_duration: 2
    nitro_cooldown: 5
    density: 1.2
    friction: 0.4
    restitution: 0.15
    linear_damping: 1.8
    angular_damping: 1.8
    drift_factor: 0.50

  - name: "Classic"
    width: 2.5
    height: 1.5
    description: "Equilibrado, sin puntos débiles"
    max_speed: 150
    acceleration: 80
    control: 7.7
    health: 110
    mass: 1.0
    nitro_multiplier: 1.5
    nitro_duration: 3
    nitro_cooldown: 5
    density: 1.2
    friction: 0.2
    restitution: 0.15
    linear_damping: 0.9
    angular_damping: 5.0
    drift_factor: 0.60

  - name: "Offroad"
    width: 1.6
    height: 1.1
    description: "Excelente tracción y peso medio"
    max_speed: 110
    acceleration: 30
    control: 8.5
    health: 120
    mass: 2.5
    nitro_multiplier: 1.4
    nitro_duration: 4
    nitro_cooldown: 6
    density: 1.2
    friction: 0.2
    restitution: 0.15
    linear_damping: 0.5
    angular_damping: 6.0
    drift_factor: 0.66

  - name: "Ghost"
    width: 2.0
    height: 1.6
    description: "Liviano y veloz, pero muy frágil"
    max_speed: 210
    acceleration: 110
    control: 8.5
    health: 90
    mass: 1.0
    nitro_multiplier: 2.0
    nitro_duration: 2
    nitro_cooldown: 4
    density: 0.9
    friction: 0.8
    restitution: 0.25
    linear_damping: 0.5
    angular_damping: 5.0
    drift_factor: 0.50
# CIUDADES Y SUS CIRCUITOS (referencias a YAMLs de mapa, lo que generaria el editor)

cities:
  - city: "LibertyCity"
    races:
      - { map_file: "maps/liberty_city_circuito1.yaml" } #cada archivo seria un circuito distino
      - { map_file: "maps/liberty_city_circuito2.yaml" }
      - { map_file: "maps/liberty_city_circuito3.yaml" }

  - city: "SanAndreas"
    races:
      - { map_file: "maps/san_andreas_circuito1.yaml" }
      - { map_file: "maps/san_andreas_circuito2.yaml" }
      - { map_file: "maps/san_andreas_circuito3.yaml" }

  - city: "ViceCity"
    races:
      - { map_file: "maps/vice_city_circuito1.yaml" }
      - { map_file: "maps/vice_city_circuito2.yaml" }
      - { map_file: "maps/vice_city_circuito3.yaml" }
