# CONFIGURACIÓN GLOBAL (constantes)

race:
  max_players: 8
  time_limit_sec: 600        # límite por carrera (10 minutos)
  intermission_sec: 10       # pausa entre carreras

car_defaults:
  health: 100.0
  max_speed: 150.0
  acceleration: 10.0
  mass: 1.0
  control: 1.0

# Penalizaciones por mejoras de auto
# (se suman en segundos al tiempo de carrera)
penalties:
  max_speed: 3.0
  acceleration: 2.0
  control: 1.5
  health: 1.0

# CIUDADES Y SUS CIRCUITOS (referencias a YAMLs de mapa, lo que generaria el editor)

cities:
  - city: "LibertyCity"
    races:
      - { map_file: "./server/assets/liberty_city_circuito1.yaml" } #cada archivo seria un circuito distino
      - { map_file: "./server/assets/liberty_city_circuito2.yaml" }
      - { map_file: "./server/assets/liberty_city_circuito3.yaml" }

  - city: "SanAndreas"
    races:
      - { map_file: "./server/assets/san_andreas_circuito1.yaml" }
      - { map_file: "./server/assets/san_andreas_circuito2.yaml" }
      - { map_file: "./server/assets/san_andreas_circuito3.yaml" }

  - city: "ViceCity"
    races:
      - { map_file: "./server/assets/vice_city_circuito1.yaml" }
      - { map_file: "./server/assets/vice_city_circuito2.yaml" }
      - { map_file: "./server/assets/vice_city_circuito3.yaml" }